"""Assembles and runs CrewAI crews with phase execution."""

from __future__ import annotations

import asyncio
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

from autocrew.analyzer.llm_client import _backoff_delay, is_retryable_error
from autocrew.analyzer.project_model import ProjectContext
from autocrew.config import settings
from autocrew.crew.crew_logger import CrewLogger
from autocrew.crew.llm_task_executor import execute_task_with_llm
from autocrew.crew.parallel_git import run_parallel_group_with_git
from autocrew.crew.task_context import inject_task_context
from autocrew.metrics import begin_session, end_session
from autocrew.squad.squad_model import AgentConfig, AgentRole, Squad
from autocrew.tasks.task_model import TaskConfig
from autocrew.tools.file_tools import write_file
from autocrew.tools.git_tools import git_commit, git_commit_succeeded
from autocrew.tools.worktree_recovery import recover_worktrees


def _inject_context(task: TaskConfig, project_root: str) -> str:
    return inject_task_context(task, project_root)


def _execute_task_simulation(
    task: TaskConfig,
    agent: AgentConfig,
    context: ProjectContext,
    project_root: str,
    logger: CrewLogger,
) -> str:
    logger.log(f"[simulation] Running task '{task.title}' with agent {agent.name}")
    description = _inject_context(task, project_root)

    if task.output_path and task.output_format in ("file", "markdown", "code"):
        placeholder = (
            f"# {task.title}\n\n"
            f"Generated by {agent.name} for {context.project_name}\n\n"
            f"## Task\n{description[:2000]}\n"
        )
        write_file(
            task.output_path,
            placeholder,
            project_root,
            agent.can_write_to,
            enforce_scope=settings.enforce_scope,
        )
        logger.log(f"Wrote placeholder to {task.output_path}")

    git_commit(project_root, f"[autocrew] {agent.role.value}: {task.title}")
    return f"Completed: {task.title}"


def _execute_task(
    task: TaskConfig,
    agent: AgentConfig,
    context: ProjectContext,
    project_root: str,
    logger: CrewLogger,
    *,
    use_llm: bool,
    dual_router: ModelRouter | None,
    llm_call: Callable[[str], str] | None,
    skip_git_commit: bool = False,
) -> str:
    if use_llm:
        if dual_router is not None:
            llm, model_name = dual_router.for_build_task(agent, task)
            result = execute_task_with_llm(
                task,
                agent,
                context,
                project_root,
                logger,
                llm.complete,
                model_name=model_name,
            )
        elif llm_call is not None:
            result = execute_task_with_llm(
                task,
                agent,
                context,
                project_root,
                logger,
                llm_call,
            )
        else:
            raise RuntimeError("use_llm=True but no LLM client configured")
        if not skip_git_commit:
            git_commit(project_root, f"[autocrew] {agent.role.value}: {task.title}")
        return result

    result = _execute_task_simulation(task, agent, context, project_root, logger)
    return result


def _tasks_for_role(tasks: list[TaskConfig], role: str) -> list[TaskConfig]:
    return [t for t in tasks if t.assigned_agent_role == role]


def _run_phase_sequential(
    roles: list[str],
    squad: Squad,
    tasks: list[TaskConfig],
    context: ProjectContext,
    project_root: str,
    logger: CrewLogger,
    max_retries: int,
    *,
    use_llm: bool,
    dual_router: ModelRouter | None,
    llm_call: Callable[[str], str] | None,
    task_filter: set[str] | None,
    on_task_start: Callable[[AgentConfig, TaskConfig, str], None] | None = None,
    on_task_done: Callable[[AgentConfig, TaskConfig, str], None] | None = None,
    skip_git_commit: bool = False,
) -> list[str]:
    results: list[str] = []
    for role in roles:
        agent = next((a for a in squad.agents if a.role.value == role), None)
        if not agent:
            continue
        role_tasks = _tasks_for_role(tasks, role)
        for task in role_tasks:
            if task_filter is not None and task.task_id not in task_filter:
                continue
            model_label = ""
            if use_llm and dual_router is not None:
                _, model_name = dual_router.for_build_task(agent, task)
                model_label = model_name.split("/")[-1]
            if on_task_start:
                on_task_start(agent, task, model_label)
            logger.set_agent_status(agent.name, "running", task.title)
            for attempt in range(max_retries + 1):
                try:
                    result = _execute_task(
                        task,
                        agent,
                        context,
                        project_root,
                        logger,
                        use_llm=use_llm,
                        dual_router=dual_router,
                        llm_call=llm_call,
                        skip_git_commit=skip_git_commit,
                    )
                    results.append(result)
                    logger.set_agent_status(agent.name, "done", task.title)
                    if on_task_done:
                        on_task_done(agent, task, result)
                    break
                except Exception as exc:
                    if attempt >= max_retries:
                        logger.set_agent_status(agent.name, "failed", task.title)
                        if settings.continue_on_task_failure:
                            logger.log(f"Task skipped after retries (continuing): {exc}")
                            break
                        logger.log(f"Task failed after retries: {exc}")
                        raise
                    logger.log(f"Retry {attempt + 1} for {task.title}: {exc}")
                    if is_retryable_error(exc):
                        time.sleep(_backoff_delay(attempt, settings.llm_retry_backoff_seconds))
    return results


async def _run_parallel_group(
    roles: list[str],
    squad: Squad,
    tasks: list[TaskConfig],
    context: ProjectContext,
    project_root: str,
    logger: CrewLogger,
    max_retries: int,
    *,
    use_llm: bool,
    dual_router: ModelRouter | None,
    llm_call: Callable[[str], str] | None,
    task_filter: set[str] | None,
    on_task_start: Callable[[AgentConfig, TaskConfig, str], None] | None = None,
    on_task_done: Callable[[AgentConfig, TaskConfig, str], None] | None = None,
    parallel_git: bool = False,
    git_push: bool = False,
) -> list[str]:
    if parallel_git:
        results, merge_info = await run_parallel_group_with_git(
            roles,
            squad,
            tasks,
            context,
            project_root,
            logger,
            max_retries,
            run_phase_sequential=_run_phase_sequential,
            use_llm=use_llm,
            dual_router=dual_router,
            llm_call=llm_call,
            task_filter=task_filter,
            on_task_start=on_task_start,
            on_task_done=on_task_done,
            git_push=git_push,
        )
        if merge_info:
            logger.log(
                f"Parallel git: approved={merge_info.approved}, "
                f"conflicts={merge_info.conflicts_on}, fixer={merge_info.conflict_fixer_role or 'none'}"
            )
        if results or merge_info:
            return results

    async def run_role(role: str) -> list[str]:
        return await asyncio.to_thread(
            _run_phase_sequential,
            [role],
            squad,
            tasks,
            context,
            project_root,
            logger,
            max_retries,
            use_llm=use_llm,
            dual_router=dual_router,
            llm_call=llm_call,
            task_filter=task_filter,
            on_task_start=on_task_start,
            on_task_done=on_task_done,
        )

    group_results = await asyncio.gather(*[run_role(r) for r in roles])
    return [item for sublist in group_results for item in sublist]


def _limit_to_one_feature(tasks: list[TaskConfig]) -> list[TaskConfig]:
    """Keep foundation tasks plus the first debate-derived feature task."""
    foundation: list[TaskConfig] = []
    feature_tasks: list[TaskConfig] = []
    for task in tasks:
        if task.task_id.startswith("debate_"):
            feature_tasks.append(task)
        else:
            foundation.append(task)
    if not feature_tasks:
        return tasks
    return foundation + [feature_tasks[0]]


def _resolve_tasks(tasks: list[TaskConfig], limit: int) -> list[TaskConfig]:
    if settings.build_one_feature_at_a_time and limit <= 0:
        tasks = _limit_to_one_feature(tasks)
    if limit <= 0 or limit >= len(tasks):
        return tasks
    return tasks[:limit]


def run_crew(
    squad: Squad,
    tasks: list[TaskConfig],
    context: ProjectContext,
    project_root: str | None = None,
    logger: CrewLogger | None = None,
    use_crewai: bool = False,
    *,
    use_llm: bool = False,
    dual_router: DualModelRouter | None = None,
    llm_call: Callable[[str], str] | None = None,
    task_limit: int = 0,
    on_task_start: Callable[[AgentConfig, TaskConfig, str], None] | None = None,
    on_task_done: Callable[[AgentConfig, TaskConfig, str], None] | None = None,
    parallel_git: bool | None = None,
    git_push: bool | None = None,
    worktree_recovery: bool | None = None,
) -> str:
    root = project_root or context.codebase_path or "."
    Path(root).mkdir(parents=True, exist_ok=True)

    use_parallel_git = settings.parallel_git if parallel_git is None else parallel_git
    do_git_push = settings.git_push if git_push is None else git_push
    do_worktree_recovery = (
        settings.worktree_recovery if worktree_recovery is None else worktree_recovery
    )

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    log_path = str(Path(settings.logs_dir) / f"run_{timestamp}.log")
    crew_logger = logger or CrewLogger(log_path=log_path)

    begin_session(context.project_name, phase="build")
    active_tasks = _resolve_tasks(tasks, task_limit)
    allowed_ids = {t.task_id for t in active_tasks}

    for agent in squad.agents:
        crew_logger.set_agent_status(agent.name, "waiting")

    dev_roles = {
        AgentRole.BACKEND_DEV.value,
        AgentRole.FRONTEND_DEV.value,
        AgentRole.FULLSTACK_DEV.value,
        AgentRole.DEVOPS.value,
        AgentRole.DATA_ENGINEER.value,
        AgentRole.AI_ENGINEER.value,
    }

    sequential_pre = [
        r for r in squad.execution_order if r in (AgentRole.PRODUCT_OWNER.value, AgentRole.ARCHITECT.value)
    ]
    sequential_post = [
        r
        for r in squad.execution_order
        if r
        in (
            AgentRole.TESTER.value,
            AgentRole.PROGRESS_TRACKER.value,
        )
    ]

    max_retries = settings.max_retries_per_task
    all_results: list[str] = []
    run_kwargs = {
        "use_llm": use_llm,
        "dual_router": dual_router,
        "llm_call": llm_call,
        "task_filter": allowed_ids,
        "on_task_start": on_task_start,
        "on_task_done": on_task_done,
    }

    all_results.extend(
        _run_phase_sequential(
            sequential_pre, squad, tasks, context, root, crew_logger, max_retries, **run_kwargs
        )
    )

    if do_worktree_recovery:
        recover_worktrees(
            root,
            crew_logger,
            max_merges=settings.worktree_recovery_max_merges,
            min_insertions=settings.worktree_recovery_min_insertions,
        )

    parallel_kwargs = {**run_kwargs, "parallel_git": use_parallel_git, "git_push": do_git_push}

    if squad.parallel_groups and settings.parallel_execution:
        for group in squad.parallel_groups:
            results = asyncio.run(
                _run_parallel_group(
                    group, squad, tasks, context, root, crew_logger, max_retries, **parallel_kwargs
                )
            )
            all_results.extend(results)
    else:
        devs_in_order = [r for r in squad.execution_order if r in dev_roles]
        all_results.extend(
            _run_phase_sequential(
                devs_in_order, squad, tasks, context, root, crew_logger, max_retries, **run_kwargs
            )
        )

    all_results.extend(
        _run_phase_sequential(
            sequential_post, squad, tasks, context, root, crew_logger, max_retries, **run_kwargs
        )
    )

    crew_logger.flush()
    mode = "LLM" if use_llm else "simulation"
    git_note = " + parallel git" if use_parallel_git else ""
    summary = f"Crew run complete ({mode}{git_note}). {len(all_results)} tasks executed."
    if task_limit > 0 and task_limit < len(tasks):
        summary += f" (limited from {len(tasks)} total tasks)"
    crew_logger.log(summary)
    end_session(
        phase="build",
        extra={
            "use_llm": use_llm,
            "tasks_executed": len(all_results),
            "task_limit": task_limit,
        },
    )
    return summary


def run_crew_with_crewai(
    squad: Squad,
    tasks: list[TaskConfig],
    context: ProjectContext,
    project_root: str,
    logger: CrewLogger | None = None,
) -> str:
    """Full CrewAI integration when the library is available."""
    try:
        from crewai import Agent, Crew, Process, Task

        crew_logger = logger or CrewLogger()
        agents_map: dict[str, Agent] = {}

        for agent_cfg in squad.agents:
            agents_map[agent_cfg.role.value] = Agent(
                role=agent_cfg.role.value.replace("_", " ").title(),
                goal=agent_cfg.goal,
                backstory=agent_cfg.backstory,
                verbose=agent_cfg.verbose,
                allow_delegation=agent_cfg.allow_delegation,
            )

        crewai_tasks = []
        for task_cfg in tasks:
            agent = agents_map.get(task_cfg.assigned_agent_role)
            if not agent:
                continue
            crewai_tasks.append(
                Task(
                    description=_inject_context(task_cfg, project_root),
                    expected_output=task_cfg.expected_output,
                    agent=agent,
                )
            )

        crew = Crew(
            agents=list(agents_map.values()),
            tasks=crewai_tasks,
            process=Process.sequential,
            verbose=True,
            memory=True,
        )
        result = crew.kickoff()
        crew_logger.log(str(result))
        crew_logger.flush()
        return str(result)
    except ImportError:
        return run_crew(squad, tasks, context, project_root, logger)
